spring:
    datasource:
        url: jdbc:mariadb://fourwarddb.cowfpof74cuw.ap-northeast-2.rds.amazonaws.com/fourwarddb
        driverClassName: org.mariadb.jdbc.Driver
        username: fourwarddb
        password: fourwarddb
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: create
    main:
        allow-bean-definition-overriding: true
server:
    port: 9000
logging:
    level:
        org.springframework.security: debug

# spring:
#     datasource:
#         url: jdbc:mariadb://localhost:3306/mariadb
#         driverClassName: org.mariadb.jdbc.Driver
#         username: mariadb
#         password: mariadb
#     jpa:
#         hibernate:
#             ddl-auto: create
#         database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
# server:
#     port: 9000
